### ISSUE TITLE
Sitemap.xml file blank

### ISSUE THREAD

**Issue by stackpath-andrew** [audal/gatsby-plugin-yoast-sitemap#4]
Any ideas why the sitemap would be blank in production?

**Comment by Kapodeistria** [comment]
Is it totally blank, or just the XML declaration on a new line?

**Comment by verystack** [comment]
Sitemaps appear blank when the XSL is missing/resolving to another domain (illegal). The sitemap itself is still valid, and can be crawled/inspected in devtools/accessed. This is fixed with #2.
